from ..constants.hold_registers import *

TIME_TYPES = [
    {
        "name": "AC Charging Start Time",
        "register": H_AC_CHARGE_START_TIME, # 68
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC Charging End Time",
        "register": H_AC_CHARGE_END_TIME, # 69
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC Charging Start Time 1",
        "register": H_AC_CHARGE_START_TIME_1, # 70
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC Charging End Time 1",
        "register": H_AC_CHARGE_END_TIME_1, # 71
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC Charging Start Time 2",
        "register": H_AC_CHARGE_START_TIME_2, # 72
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC Charging End Time 2",
        "register": H_AC_CHARGE_END_TIME_2, # 73
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC First Load Start Time",
        "register": H_AC_FIRST_START_TIME, # 152
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC First Load End Time",
        "register": H_AC_FIRST_END_TIME, # 153
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC First Load Start Time 1",
        "register": H_AC_FIRST_START_TIME_1, # 154
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC First Load End Time 1",
        "register": H_AC_FIRST_END_TIME_1, # 155
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Peak Shaving Start Time",
        "register": H_PEAK_SHAVING_START_TIME, # 209
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Peak Shaving End Time",
        "register": H_PEAK_SHAVING_END_TIME, # 210
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Peak Shaving Start Time 1",
        "register": H_PEAK_SHAVING_START_TIME_1, # 211
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Peak Shaving End Time 1",
        "register": H_PEAK_SHAVING_END_TIME_1, # 212
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Grid",
    },
    {
        "name": "Generator Start Time",
        "register": H_GEN_START_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Generator",
    },
    {
        "name": "Generator End Time",
        "register": H_GEN_END_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Generator",
    },
    {
        "name": "Generator Start Time 1",
        "register": H_GEN_START_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Generator",
    },
    {
        "name": "Generator End Time 1",
        "register": H_GEN_END_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:engine-off-outline",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Generator",
    },
    {
        "name": "Forced Discharge Start Time",
        "register": H_FORCED_DISCHARGE_START_TIME, # 84
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Forced Discharge End Time",
        "register": H_FORCED_DISCHARGE_END_TIME, # 85
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Forced Discharge Start Time 1",
        "register": H_FORCED_DISCHARGE_START_TIME_1, # 86
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Forced Discharge End Time 1",
        "register": H_FORCED_DISCHARGE_END_TIME_1, # 87
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Forced Discharge Start Time 2",
        "register": H_FORCED_DISCHARGE_START_TIME_2, # 88
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "Forced Discharge End Time 2",
        "register": H_FORCED_DISCHARGE_END_TIME_2, # 89
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },

    # ===========================================================================================
    # 7-DAY SCHEDULING TIME ENTITIES (Registers 500-723)
    # ===========================================================================================

    # --- AC Charge Schedule Time Entities ---

    {
        "name": "AC Charge Start Time 1 Mon",
        "register": H_AC_CHG_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 1 Mon",
        "register": H_AC_CHG_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 2 Mon",
        "register": H_AC_CHG_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 2 Mon",
        "register": H_AC_CHG_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 1 Tue",
        "register": H_AC_CHG_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 1 Tue",
        "register": H_AC_CHG_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 2 Tue",
        "register": H_AC_CHG_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 2 Tue",
        "register": H_AC_CHG_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 1 Wed",
        "register": H_AC_CHG_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 1 Wed",
        "register": H_AC_CHG_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 2 Wed",
        "register": H_AC_CHG_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 2 Wed",
        "register": H_AC_CHG_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 1 Thu",
        "register": H_AC_CHG_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 1 Thu",
        "register": H_AC_CHG_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 2 Thu",
        "register": H_AC_CHG_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 2 Thu",
        "register": H_AC_CHG_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 1 Fri",
        "register": H_AC_CHG_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 1 Fri",
        "register": H_AC_CHG_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 2 Fri",
        "register": H_AC_CHG_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 2 Fri",
        "register": H_AC_CHG_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 1 Sat",
        "register": H_AC_CHG_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 1 Sat",
        "register": H_AC_CHG_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 2 Sat",
        "register": H_AC_CHG_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 2 Sat",
        "register": H_AC_CHG_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 1 Sun",
        "register": H_AC_CHG_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 1 Sun",
        "register": H_AC_CHG_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge Start Time 2 Sun",
        "register": H_AC_CHG_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "AC Charge End Time 2 Sun",
        "register": H_AC_CHG_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },

    # --- Forced Charge Schedule Time Entities ---

    {
        "name": "Forced Charge Start Time 1 Mon",
        "register": H_FORCED_CHG_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 1 Mon",
        "register": H_FORCED_CHG_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 2 Mon",
        "register": H_FORCED_CHG_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 2 Mon",
        "register": H_FORCED_CHG_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 1 Tue",
        "register": H_FORCED_CHG_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 1 Tue",
        "register": H_FORCED_CHG_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 2 Tue",
        "register": H_FORCED_CHG_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 2 Tue",
        "register": H_FORCED_CHG_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 1 Wed",
        "register": H_FORCED_CHG_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 1 Wed",
        "register": H_FORCED_CHG_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 2 Wed",
        "register": H_FORCED_CHG_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 2 Wed",
        "register": H_FORCED_CHG_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 1 Thu",
        "register": H_FORCED_CHG_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 1 Thu",
        "register": H_FORCED_CHG_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 2 Thu",
        "register": H_FORCED_CHG_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 2 Thu",
        "register": H_FORCED_CHG_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 1 Fri",
        "register": H_FORCED_CHG_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 1 Fri",
        "register": H_FORCED_CHG_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 2 Fri",
        "register": H_FORCED_CHG_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 2 Fri",
        "register": H_FORCED_CHG_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 1 Sat",
        "register": H_FORCED_CHG_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 1 Sat",
        "register": H_FORCED_CHG_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 2 Sat",
        "register": H_FORCED_CHG_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 2 Sat",
        "register": H_FORCED_CHG_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 1 Sun",
        "register": H_FORCED_CHG_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 1 Sun",
        "register": H_FORCED_CHG_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge Start Time 2 Sun",
        "register": H_FORCED_CHG_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Charge End Time 2 Sun",
        "register": H_FORCED_CHG_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },

    # --- Forced Discharge Schedule Time Entities ---

    {
        "name": "Forced Discharge Start Time 1 Mon",
        "register": H_FORCED_DISCHG_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 1 Mon",
        "register": H_FORCED_DISCHG_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 2 Mon",
        "register": H_FORCED_DISCHG_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 2 Mon",
        "register": H_FORCED_DISCHG_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 1 Tue",
        "register": H_FORCED_DISCHG_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 1 Tue",
        "register": H_FORCED_DISCHG_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 2 Tue",
        "register": H_FORCED_DISCHG_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 2 Tue",
        "register": H_FORCED_DISCHG_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 1 Wed",
        "register": H_FORCED_DISCHG_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 1 Wed",
        "register": H_FORCED_DISCHG_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 2 Wed",
        "register": H_FORCED_DISCHG_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 2 Wed",
        "register": H_FORCED_DISCHG_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 1 Thu",
        "register": H_FORCED_DISCHG_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 1 Thu",
        "register": H_FORCED_DISCHG_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 2 Thu",
        "register": H_FORCED_DISCHG_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 2 Thu",
        "register": H_FORCED_DISCHG_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 1 Fri",
        "register": H_FORCED_DISCHG_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 1 Fri",
        "register": H_FORCED_DISCHG_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 2 Fri",
        "register": H_FORCED_DISCHG_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 2 Fri",
        "register": H_FORCED_DISCHG_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 1 Sat",
        "register": H_FORCED_DISCHG_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 1 Sat",
        "register": H_FORCED_DISCHG_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 2 Sat",
        "register": H_FORCED_DISCHG_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 2 Sat",
        "register": H_FORCED_DISCHG_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 1 Sun",
        "register": H_FORCED_DISCHG_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 1 Sun",
        "register": H_FORCED_DISCHG_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge Start Time 2 Sun",
        "register": H_FORCED_DISCHG_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Forced Discharge End Time 2 Sun",
        "register": H_FORCED_DISCHG_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },

    # --- Peak Shaving Schedule Time Entities ---

    {
        "name": "Peak Shaving Start Time 1 Mon",
        "register": H_PEAK_SHAV_TIME1_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 1 Mon",
        "register": H_PEAK_SHAV_TIME1_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 2 Mon",
        "register": H_PEAK_SHAV_TIME2_START_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 2 Mon",
        "register": H_PEAK_SHAV_TIME2_END_MON,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 1 Tue",
        "register": H_PEAK_SHAV_TIME1_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 1 Tue",
        "register": H_PEAK_SHAV_TIME1_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 2 Tue",
        "register": H_PEAK_SHAV_TIME2_START_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 2 Tue",
        "register": H_PEAK_SHAV_TIME2_END_TUE,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 1 Wed",
        "register": H_PEAK_SHAV_TIME1_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 1 Wed",
        "register": H_PEAK_SHAV_TIME1_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 2 Wed",
        "register": H_PEAK_SHAV_TIME2_START_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 2 Wed",
        "register": H_PEAK_SHAV_TIME2_END_WED,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 1 Thu",
        "register": H_PEAK_SHAV_TIME1_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 1 Thu",
        "register": H_PEAK_SHAV_TIME1_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 2 Thu",
        "register": H_PEAK_SHAV_TIME2_START_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 2 Thu",
        "register": H_PEAK_SHAV_TIME2_END_THU,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 1 Fri",
        "register": H_PEAK_SHAV_TIME1_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 1 Fri",
        "register": H_PEAK_SHAV_TIME1_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 2 Fri",
        "register": H_PEAK_SHAV_TIME2_START_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 2 Fri",
        "register": H_PEAK_SHAV_TIME2_END_FRI,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 1 Sat",
        "register": H_PEAK_SHAV_TIME1_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 1 Sat",
        "register": H_PEAK_SHAV_TIME1_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 2 Sat",
        "register": H_PEAK_SHAV_TIME2_START_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 2 Sat",
        "register": H_PEAK_SHAV_TIME2_END_SAT,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 1 Sun",
        "register": H_PEAK_SHAV_TIME1_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 1 Sun",
        "register": H_PEAK_SHAV_TIME1_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving Start Time 2 Sun",
        "register": H_PEAK_SHAV_TIME2_START_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    {
        "name": "Peak Shaving End Time 2 Sun",
        "register": H_PEAK_SHAV_TIME2_END_SUN,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Schedules",
    },
    # --- Charge First Times ---
    {
        "name": "Charge First Start Time",
        "register": H_CHARGE_FIRST_START_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Charge First End Time",
        "register": H_CHARGE_FIRST_END_TIME,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Charge First Start Time 1",
        "register": H_CHARGE_FIRST_START_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Charge First End Time 1",
        "register": H_CHARGE_FIRST_END_TIME_1,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Charge First Start Time 2",
        "register": H_CHARGE_FIRST_START_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },
    {
        "name": "Charge First End Time 2",
        "register": H_CHARGE_FIRST_END_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
        "device_group": "Battery",
    },

    # --- AC First Period 2 Times ---
    {
        "name": "AC First Load Start Time 2",
        "register": H_AC_FIRST_START_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-start",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },
    {
        "name": "AC First Load End Time 2",
        "register": H_AC_FIRST_END_TIME_2,
        "register_type": "hold",
        "extract": lambda reg: (reg & 0xFF, (reg >> 8) & 0xFF),
        "compose": lambda hour, minute: (hour & 0xFF) | ((minute & 0xFF) << 8),
        "icon": "mdi:clock-end",
        "enabled": True,
        "visible": True,
        "master_only": True,
    },


]
